[tools]
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:aristocratos/btop" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:cli/cli" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:earendil-works/pi" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:fastfetch-cli/fastfetch" = "latest"
"aqua:herdrdev/herdr" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:modem-dev/hunk" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:starship/starship" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:yorukot/superfile" = "latest"
"github:AlexsJones/llmfit" = "latest"
"github:can1357/oh-my-pi" = "latest"
"github:hpjansson/chafa" = "latest"
"github:reyamira/models" = "latest"
"github:sinelaw/fresh" = "latest"
go = "latest"
node = "latest"
"npm:vite-plus" = "latest"
pnpm = "latest"
rust = "latest"
