[tools]
"aqua:cli/cli" = "latest"
"aqua:neovim/neovim" = "latest"
atuin = "latest"
bat = "latest"
btop = "latest"
delta = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
"github:hpjansson/chafa" = "latest"
"github:reyamira/models" = "latest"
"github:sinelaw/fresh" = "latest"
go = "latest"
herdr = "latest"
hunk = "latest"
jq = "latest"
lazygit = "latest"
llmfit = "latest"
neovim = "latest"
oh-my-pi = { version = "latest", rename_exe = "omp" }
pi = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
superfile = "latest"
tealdeer = "latest"
uv = "latest"
zoxide = "latest"
